[build]
  publish = "public"
  functions = "netlify/functions"
  command = "chmod +x netlify/functions/setup.sh && ./netlify/functions/setup.sh"

[functions]
  node_bundler = "esbuild"
  included_files = ["bin/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
