[build]
  publish = "."
  functions = "functions"
  command = "chmod +x functions/setup.sh && ./functions/setup.sh"

[functions]
  node_bundler = "esbuild"
  included_files = ["bin/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200